### ISSUE TITLE
SARV3 Cancelling Mission causes error/server hang

### ISSUE THREAD

**Issue by Grizlog** [WonderingPonY/GVSAR#80]
After registering, when user cancels mission, error occurs and the server hangs.

Steps to re-create
1. Hop in any Beirut Spawn
2. Register for mission
3. Wait for mission to be assigned
4. Cancel Mission

![image](https://github.com/WonderingPonY/GVSAR/assets/91765122/666faad3-b757-4de2-9a7a-2036aa1255b8)

Line 29 error
![image](https://github.com/WonderingPonY/GVSAR/assets/91765122/13ed8120-7b29-4d21-a031-5f110709e490)

Line 294 error
![image](https://github.com/WonderingPonY/GVSAR/assets/91765122/b94d6398-a37c-4b01-a03f-15a155153439)

Line 220 error
![image](https://github.com/WonderingPonY/GVSAR/assets/91765122/c3919954-f4ba-47d2-ac61-69b718ba9d82)

**Comment by WonderingPonY** [comment]
removed missions temporarily to focus on larger issues

**Comment by WonderingPonY** [comment]
Re-added the missions, Fixed the error in LebanonMissions.lua
