### ISSUE TITLE
SARV3 "Register" button not disappearing after selecting

### ISSUE THREAD

**Issue by Grizlog** [WonderingPonY/GVSAR#81]
In any Haifa slot, registering for missions doesn't remove "register" option from menu, multiple "register" buttons populate menu after cancelling mission. Switching slots does not remove old missions

Steps to re-create
1. Hop in any Haifa slot
2. Register for mission
3. Cancel mission
4. Re-Register for mission

![image](https://github.com/WonderingPonY/GVSAR/assets/91765122/1c389e09-22ea-4c6e-bed5-81e99d0f63c3)

**Comment by WonderingPonY** [comment]
You should not have to re-register for missions. 
Register has been removed once you register.
