### ISSUE TITLE
Hospitals not marks on F10 map

### ISSUE THREAD

**Issue by Grizlog** [WonderingPonY/GVSAR#84]
Carmel Healthcare Centre (Israel), Rambam Healthcare Centre(Israel), and Saint George University Hospital (Lebanon) have no Mission Markers on F10 map

**Comment by WonderingPonY** [comment]
When adding the marks for the hospitals, good colouring and wording is a must. 
Should make sure we use the 'real' names of the hospital. In English of course

**Comment by Grizlog** [comment]
100% agree, I will probably need help scripting it in something other than MIST or MOOSE

**Comment by WonderingPonY** [comment]
Just use the built in marks like we did in the previous version. 
![Screenshot 2023-11-24 210332](https://github.com/WonderingPonY/GVSAR/assets/13998027/30762c9d-e5c5-44b9-b515-32af1e0bca85)

**Comment by Grizlog** [comment]
Labels have been added to the mission. Closing Issue
